// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc1YrpOEGCoXqf2WDiV3BnxqqaHPN3UZk',
    appId: '1:273584666032:web:3f3e7be93e258f62aa5275',
    messagingSenderId: '273584666032',
    projectId: 'flutterchatapp-3a39d',
    authDomain: 'flutterchatapp-3a39d.firebaseapp.com',
    storageBucket: 'flutterchatapp-3a39d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxddQWNBow7Vf-Wy9XmXStHFTSqorpp4',
    appId: '1:273584666032:android:f155f90cc68155a8aa5275',
    messagingSenderId: '273584666032',
    projectId: 'flutterchatapp-3a39d',
    storageBucket: 'flutterchatapp-3a39d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo7FMd5pObIkmp7vgMeTIs8gNqDRuqVl4',
    appId: '1:273584666032:ios:4360d18557d06468aa5275',
    messagingSenderId: '273584666032',
    projectId: 'flutterchatapp-3a39d',
    storageBucket: 'flutterchatapp-3a39d.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo7FMd5pObIkmp7vgMeTIs8gNqDRuqVl4',
    appId: '1:273584666032:ios:3078b5c00267fe11aa5275',
    messagingSenderId: '273584666032',
    projectId: 'flutterchatapp-3a39d',
    storageBucket: 'flutterchatapp-3a39d.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
